---
- name: Create Ubuntu VM
  hosts: localhost
  connection: local 
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
tasks:
    - name: Create new Ubuntu VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_hostname }}"
        cluster: "{{ vcenter_cluster }}"
        template: "{{ template_name }}"
        customization_spec:
          domain: "{{ domain_name }}"
          dns_servers: "{{ dns_servers }}"
          ip_address: "{{ ip_address }}"
          subnet_mask: "{{ subnet_mask }}"
          gateway: "{{ gateway }}"
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ vcpu }}"
          scsi: paravirtual
        disk:
          - size_gb: "{{ disk_size }}"
            type: thin
        state: present
